### ISSUE TITLE
[BUG] HA 2024.02.0 integration not start

### ISSUE THREAD

**Issue by Saentist** [WouterTuinstra/Homeassistant-Growatt-Local-Modbus#27]
After update Integration do not start

```
Core 2024.2.0
Supervisor 2024.01.1
Operating System 11.5
Frontend 20240207.0
```

```
Invalid config
The following integrations and platforms could not be set up:
growatt_local Show logs
```

```py
Logger: homeassistant.setup
Source: setup.py:251
First occurred: 08:49:19 ч. (1 occurrences)
Last logged: 08:49:19 ч.

Setup failed for custom integration 'growatt_local': Unable to import component: cannot import name 'ModbusBaseClient' from 'pymodbus.client' (/usr/local/lib/python3.12/site-packages/pymodbus/client/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/growatt_local/__init__.py", line 56, in <module>
    from .API.growatt import GrowattDevice, GrowattSerial, GrowattNetwork
  File "/config/custom_components/growatt_local/API/growatt.py", line 17, in <module>
    from pymodbus.client import ModbusBaseClient
ImportError: cannot import name 'ModbusBaseClient' from 'pymodbus.client' (/usr/local/lib/python3.12/site-packages/pymodbus/client/__init__.py)

```

**Comment by WouterTuinstra** [comment]
Which version is currently installed of pymodbus because there is a range of releases where the `ModbusBaseClient` in not included in the pymodbus/client/\_\_init__.py this has been fixed in the most recent release 3.6.4 
see also following commit: https://github.com/pymodbus-dev/pymodbus/commit/66af5b67058605c81854e872b0ff3f612dcb278e

**Comment by Saentist** [comment]
Any example how to get version?
I use Home Assistant HAOS in ESXI server
https://www.home-assistant.io/installation/alternative 
everything is preinstalled

**Comment by Saentist** [comment]
```
Support for pyModbus below 3.5.2 has been dropped, for HA installations older than 2023.9.0
Integration 2023.09.3 is the last supported version
```

No idea what is current version.

**Comment by Nick-Innes** [comment]
I'm suffering the same error message, and the integration failing to start once I upgraded from 2024.1.x to 2024.2.1, and the issue persists after upgrading to 2024.2.2, and removing and reinstalling the integration via HACS.

**Comment by Saentist** [comment]
How you remove it it's impossible, delete not working?

**Comment by Nick-Innes** [comment]
I removed the folder below custom_components and then told HACS to ignore that it was configured. I then restarted home assistant a couple of times and reinstalled using HACS, only to find I was exactly where I'd started.
I'd been hoping that 2024.2.2 or later would maybe update pyModbus or similar, but no such luck.
I've nothing else using Modbus, except the GivTCP add-on, but that's in a different container.

**Comment by WouterTuinstra** [comment]
I updated the `manifest.json` file with the requirements to use the latest version of pymodbus this should automatically solve the issue because HA will check the required packages.

**Comment by Saentist** [comment]
Still have this message

```
Invalid config
The following integrations and platforms could not be set up:

[growatt_local] ([Show logs])
Please check your config and [logs].
```
```py
Logger: homeassistant.setup
Source: setup.py:251
First occurred: 17:03:58 ч. (1 occurrences)
Last logged: 17:03:58 ч.

Setup failed for custom integration 'growatt_local': Unable to import component: cannot import name 'ModbusBaseClient' from 'pymodbus.client' (/usr/local/lib/python3.12/site-packages/pymodbus/client/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/growatt_local/__init__.py", line 56, in <module>
    from .API.growatt import GrowattDevice, GrowattSerial, GrowattNetwork
  File "/config/custom_components/growatt_local/API/growatt.py", line 17, in <module>
    from pymodbus.client import ModbusBaseClient
ImportError: cannot import name 'ModbusBaseClient' from 'pymodbus.client' (/usr/local/lib/python3.12/site-packages/pymodbus/client/__init__.py)

```

**Comment by WouterTuinstra** [comment]
Have you updated the integration because I have no issues. At restart it should state the following:
Attempting install of pymodbus>=3.6.4

**Comment by WouterTuinstra** [comment]
I don't know why it would not update on your side best to otherwise do it manual but I don't know how to get access to Home Assistant in an ESXI environment

**Comment by WouterTuinstra** [comment]
Use the "Advanced SSH & Web Terminal" and execute the following commands:
`pip show pymodbus`
`pip install pymodbus==3.6.4`

**Comment by Saentist** [comment]
I guess i need to be in some docker crap before call this 
![image](https://github.com/WouterTuinstra/Homeassistant-Growatt-Local-Modbus/assets/16975883/df5eab99-47e4-46d5-a8c6-37704289fd56)

Strange before it was working
 
Second command do something
![image](https://github.com/WouterTuinstra/Homeassistant-Growatt-Local-Modbus/assets/16975883/46c40bb8-2249-4e49-a613-2a1cc3df363a)

And after restart it work, but sun is not enough to see values.

**Comment by WouterTuinstra** [comment]
Strange that initially not even recognized the package.

**Comment by Nick-Innes** [comment]
Thank you! I updated the custom component yesterday and when the sun returned today everything worked perfectly again!

**Comment by Saentist** [comment]
@WouterTuinstra just after update to [Release 2024.2.3](https://www.home-assistant.io/blog/2024/02/07/release-20242/#release-202423---february-22)
immediately block integration and need  to install `pymodbus` again.

other integration with use pymodbus have this:
```yaml
"requirements": ["pymodbus>=3.5.2"],
"version": "2024.02.6"
```

**Comment by WouterTuinstra** [comment]
I'm not sure why it's not installing `pymodbus` but that would be a problem in HA itself and not in this intergration.

**Comment by Saentist** [comment]
> I'm not sure why it's not installing `pymodbus` but that would be a problem in HA itself and not in this intergration.

Solax integration use it but not sure how, without need to install it as in this case.

https://github.com/home-assistant/core/tree/dev/homeassistant/components/modbus
```
# homeassistant.components.modbus
pymodbus==3.6.4
```

I see some string 
```py
from pymodbus.exceptions import ModbusException
import pytest
```
not sure is this connected

**Comment by Saentist** [comment]
@WouterTuinstra 
Again update again failed to start
reload missing, need full reload of HA
![image](https://github.com/WouterTuinstra/Homeassistant-Growatt-Local-Modbus/assets/16975883/b8cc2f0d-197d-44df-b5aa-13e5106c3e26)
need to be something as this 
![image](https://github.com/WouterTuinstra/Homeassistant-Growatt-Local-Modbus/assets/16975883/05262cd0-c137-4f56-a0ce-cb19305a5edc)
after install pymodbus
![image](https://github.com/WouterTuinstra/Homeassistant-Growatt-Local-Modbus/assets/16975883/8de5a208-d2bb-4cd8-bc06-3976b97fe25d)

**Comment by Saentist** [comment]
@WouterTuinstra 
today's update show pymodbus as installed but there is some difference.

```py
Logger: homeassistant.setup
Source: setup.py:251
First occurred: 15:09:35 ч. (1 occurrences)
Last logged: 15:09:35 ч.

Setup failed for custom integration 'growatt_local': Unable to import component: cannot import name 'ModbusBaseClient' from 'pymodbus.client' (/usr/local/lib/python3.12/site-packages/pymodbus/client/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/growatt_local/__init__.py", line 56, in <module>
    from .API.growatt import GrowattDevice, GrowattSerial, GrowattNetwork
  File "/config/custom_components/growatt_local/API/growatt.py", line 17, in <module>
    from pymodbus.client import ModbusBaseClient
ImportError: cannot import name 'ModbusBaseClient' from 'pymodbus.client' (/usr/local/lib/python3.12/site-packages/pymodbus/client/__init__.py) 
```

but pymodbus is in different location

![image](https://github.com/WouterTuinstra/Homeassistant-Growatt-Local-Modbus/assets/16975883/9c002231-d387-4b16-98c7-49728ca22806)

![image](https://github.com/WouterTuinstra/Homeassistant-Growatt-Local-Modbus/assets/16975883/e4ded0e6-c44d-48c4-873c-c0dbc49a0ec1)
