### ISSUE TITLE
[BUG] not working on HA 2024.1.6

### ISSUE THREAD

**Issue by Saentist** [WouterTuinstra/Homeassistant-Growatt-Local-Modbus#22]
Home Assistant OS, OVA virtual machine 

```php
Core 2024.1.6
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0
```
When setup integration there is a message 

```js
Config flow could not be loaded: {"message":"Invalid handler specified"}
```

in logs there is:

```js
Logger: homeassistant.config_entries
Source: config_entries.py:2087
First occurred: 2 февруари 2024 г. в 15:28:06 ч. (6 occurrences)
Last logged: 00:20:59 ч.

Error occurred loading flow for integration growatt_local: cannot import name 'Defaults' from 'pymodbus.constants' (/usr/local/lib/python3.11/site-packages/pymodbus/constants.py)
```
